- hosts: localhost
  name: Run local installs
  roles:
    - workstation

- hosts: localhost
  become: yes
  vars:
    ohmyzsh_users:
      - "{{ user }}"
  roles:
    - role: gantsign.bat
      tags: ubuntu

    - role: nover.ohmyzsh
      ohmyzsh_users:
        - "{{ ohmyzsh_user }}"

    - role: geerlingguy.docker
      tags: ubuntu
      docker_apt_release_channel: "test"
      docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} focal {{ docker_apt_release_channel }}"

    - role: hurricanehrndz.rustup
      become: true
      rustup_user: "{{ user }}"
      rustup_cargo_crates:
        - alacritty
        - ripgrep
        - starship

    - role: nephelaiio.tmux
      ansible_user: "{{ user }}"
      tmux_conf_template: "{{ playbook_dir }}/templates/tmux.conf"

    - role: ableton.nix
      ansible_user: "{{ user }}"

# This needs to come last
- hosts: localhost
  roles:
    - configure
  tags: configure
