---
- name: Run Ansible Galaxy
  hosts: localhost
  become: true
  tasks:
    - local_action: command ansible-galaxy install -r requirements.yml

- name: Install Dev Tools
  hosts: localhost
  become: yes
  vars:
    ohmyzsh_theme: robbyrussell
    ohmyzsh_users: [ "{{ user }}" ]
  roles:
    - { role: nover.ohmyzsh, ohmyzsh_users: [ "{{ ohmyzsh_user }}" ] }
    - Tahvok.vim
    - { role: nephelaiio.tmux, tmux_packages: tmux, ansible_user: "{{ user }}", tmux_conf_template: "{{ playbook_dir }}/templates/tmux.conf" }

- name: Default to Zsh
  hosts: localhost
  become: yes
  tasks:
    - user:
        name: "{{ user|quote }}"
        generate_ssh_key: yes
        shell: /usr/bin/zsh
        append: yes
        groups: adm, docker

- name: Install useful packages
  hosts: localhost
  become: yes
  tasks:
    - action:  >
        {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
      with_items:
        - docker.io
        - htop
        - net-tools
        - tree
        - jq
        - httpie
        - cowsay
        - lolcat
        - toilet
        - ubuntu-restricted-extras
        - powerline
        - gnome-tweaks
        - fonts-powerline

# TODO: wait for Ansible 2.8 and snap command
- name: Install Slack via Snap
  hosts: localhost
  become: yes
  tasks:
    - command: snap install --classic slack

- name: Install Bat
  hosts: localhost
  roles:
    - role: gantsign.bat

- name: Install latest Haskell Stack
  hosts: localhost
  tasks:
    - shell: which stack || curl -sSL https://get.haskellstack.org/ | sh

- name: Install NodeJS
  hosts: localhost
  become: yes
  tasks:
     - get_url:
         url: https://deb.nodesource.com/setup_10.x
         dest: /tmp/set-up-node-10.sh
         force: yes
         mode: ug+rx
     - script: /tmp/set-up-node-10.sh
     - apt:
         name: nodejs

- name: Install GHC etc
  hosts: localhost
  tasks:
    - command: stack setup

- name: Install Rust
  hosts: localhost
  tasks:
    - get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        force: yes
        mode: ug+x
    - script: /tmp/rustup.sh -y


- name: Sort out window dragging
  hosts: localhost
  tasks:
    - command: gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier '<Alt>'

- name: Reminders
  hosts: localhost
  tasks:
    - command: echo "Get Alacritty - https://github.com/jwilm/alacritty/releases/latest"
