---
- name: Run Ansible Galaxy
  hosts: localhost
  become: true
  tasks:
    - local_action: command ansible-galaxy install -r requirements.yml

- name: Install Dev Tools
  hosts: localhost
  become: yes
  vars:
    ohmyzsh_theme: robbyrussell
    ohmyzsh_users: [ "{{ user }}" ]
  roles:
    - { role: nover.ohmyzsh, ohmyzsh_users: [ "{{ ohmyzsh_user }}" ] }
    - Tahvok.vim
    - { role: nephelaiio.tmux, tmux_packages: tmux, ansible_user: "{{ user }}", tmux_conf_template: "{{ playbook_dir }}/templates/tmux.conf" }

- name: Configure Zsh
  hosts: localhost
  tasks:
    - template:
        src: templates/zshrc.in
        dest: "{{ ansible_env.HOME + '/.config/.zshrc' }}"
        backup: yes
    - file:
        src: "{{ ansible_env.HOME + '/.config/.zshrc' }}"
        dest: "{{ ansible_env.HOME + '/.zshrc' }}"
        state: link
        force: true
    - file:
        path: "{{ ansible_env.HOME + '/.conf/' }}"
        state: absent

- name: Configure Tmux
  hosts: localhost
  tasks:
    - template:
        src: templates/tmux.conf
        dest: "{{ ansible_env.HOME + '/.config/tmux.conf' }}"
    - file:
        src: "{{ ansible_env.HOME + '/.config/tmux.conf' }}"
        dest: "{{ ansible_env.HOME + '/.tmux.conf' }}"
        state: link

- name: Add Yarn repo
  hosts: localhost
  become: true
  tasks:
    - apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present
    - apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: present
        filename: yarn
    - apt:
        update_cache: true
        name: yarn

- name: Add Oracle Java repo
  hosts: localhost
  become: true
  tasks:
   - apt_repository:
       repo: "ppa:linuxuprising/java"
       state: present
       filename: linuxuprising
   - shell: echo "oracle-java11-installer shared/accepted-oracle-license-v1-2 select true" | debconf-set-selections
   - apt:
       update_cache: true
       name: oracle-java11-installer 


- name: Install useful packages
  hosts: localhost
  become: yes
  tasks:
    - action:  >
        {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
      with_items:
        - openjdk-11-jdk
        - python3-pip
        - python3-venv
        - docker.io
        - pandoc
        - htop
        - net-tools
        - tree
        - jq
        - httpie
        - cowsay
        - lolcat
        - toilet
        - ubuntu-restricted-extras
        - powerline
        - gnome-tweaks
        - fonts-powerline

# TODO: wait for Ansible 2.8 and snap command
- name: Install Slack via Snap
  hosts: localhost
  become: yes
  tasks:
    - command: snap install --classic slack

- name: Install Bat
  hosts: localhost
  roles:
    - role: gantsign.bat

- name: Set up Python tooling
  hosts: localhost
  tasks:
    - command: python3 -m pip install --user --upgrade pip
    - command: pip install --user poetry

- name: Install latest Haskell Stack
  hosts: localhost
  tasks:
    - shell: which stack || curl -sSL https://get.haskellstack.org/ | sh

- name: Install NodeJS
  hosts: localhost
  become: yes
  tasks:
     - get_url:
         url: https://deb.nodesource.com/setup_10.x
         dest: /tmp/set-up-node-10.sh
         force: yes
         mode: ug+rx
     - script: /tmp/set-up-node-10.sh
     - apt:
         name: nodejs

- name: Install GHC etc
  hosts: localhost
  tasks:
    - command: stack setup

- name: Install Rust
  hosts: localhost
  tasks:
    - get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        force: yes
        mode: ug+x
    - script: /tmp/rustup.sh -y

- name: Configure user for Zsh and Docker
  hosts: localhost
  become: yes
  tasks:
    - user:
        name: "{{ user|quote }}"
        generate_ssh_key: yes
        shell: /usr/bin/zsh
        append: yes
        groups: adm, docker


- name: Sort out window dragging
  hosts: localhost
  tasks:
    - command: gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier '<Alt>'

- name: Reminders
  hosts: localhost
  tasks:
    - command: echo "Get Alacritty - https://github.com/jwilm/alacritty/releases/latest"

- name: Increase file watchers
  hosts: localhost
  become: true
  tasks:
   - command: echo "fs.inotify.max_user_watches=524288" >>> /etc/sysctl.conf

- name: Sort arrow keys
  hosts: localhost
  tasks:
   - command: gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "[]"
   - command: gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "[]"
