---
- name: Run Ansible Galaxy
  hosts: localhost
  become: true
  tasks:
    - local_action: command ansible-galaxy install -r requirements.yml

- name: Install Dev Tools 
  hosts: localhost
  #become_user: {{ user }}
  vars:
    ohmyzsh_theme: robbyrussell
    ohmyzsh_users: [ "{{ user }}" ]
  roles:
    - { role: nover.ohmyzsh, ohmyzsh_users: [ "{{ ohmyzsh_user }}" ] }
    - Tahvok.vim
    - { role: nephelaiio.tmux, tmux_packages: tmux, ansible_user: "{{ user }}", tmux_conf_template: "{{ playbook_dir }}/templates/tmux.conf" }

- name: Install useful packages
  hosts: localhost
  become: yes
  tasks:
    - action:  >
        {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes 
      with_items:
        - docker.io
        - htop
        - net-tools
        - tree
        - jq
        - httpie
        - cowsay
        - lolcat
        - toilet
        - ubuntu-restricted-extras
        - powerline

- name: Install Bat
  hosts: localhost
  roles:
    - role: gantsign.bat
    - role: gantsign.antigen
      users:
        - username: "{{ user }}"
          antigen_bundles:
            - name: bat
              url: gantsign/zsh-plugins
              location: bat

- name: Install latest Haskell Stack
  hosts: localhost
  tasks:
    - shell: which stack || curl -sSL https://get.haskellstack.org/ | sh

- name: Install GHC etc
  hosts: localhost
  tasks:
    - command: stack setup

- name: Reminders
  hosts: localhost
  tasks:
    - command: echo "Get Alacritty - https://github.com/jwilm/alacritty/releases/latest"
