- name: nover.ohmyzsh
  src: nover.ohmyzsh
- name: Tahvok.vim
  src: Tahvok.vim
  #- name: kbrebanov.tmux
  # src: kbrebanov.tmux
- name: nephelaiio.tmux
  src: nephelaiio.tmux
- name: gantsign.bat
  src: gantsign.bat
- name: geerlingguy.docker
  src: geerlingguy.docker
- name: hurricanehrndz.rustup
  src: hurricanehrndz.rustup
