---
- name: Install Arch-specific apps
  become: yes
  package:
    state: latest
    name:
      - docker
      - "jdk{{ arch_openjdk_version }}-openjdk"
      - ttf-meslo-nerd-font-powerlevel10k
      - bat

- name: Install Node JS LTS
  become: true
  package:
    name: nodejs-lts-gallium
    state: latest

# TODO: Poetry + AWSCLI
