---
- name: Install gpg
  become: yes
  apt:
    update_cache: true
    name: gpg

- name: Add Yarn APT key
  become: true
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add Yarn repo
  become: true
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
    filename: yarn

- name: Add Kubernetes Key
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add Kubernetes repo
  become: true
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main


- name: Get Signal key
  get_url:
    url: https://updates.signal.org/desktop/apt/keys.asc
    dest: /tmp/signal-key.asc
    force: yes

- name: Convert Signal key
  shell: |
    rm -f /tmp/signal-desktop-keyring.gpg
    gpg --dearmor -o /tmp/signal-desktop-keyring.gpg /tmp/signal-key.asc
    rm /tmp/signal-key.asc

- name: Install Signal GPG key
  become: true
  copy:
    src: /tmp/signal-desktop-keyring.gpg
    dest: /usr/share/keyrings/signal-desktop-keyring.gpg
    force: true

- name: Add Signal repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main"
    state: present
    filename: signal-xenial

- name: Install Slack, Noson via Snap
  snap:
    classic: true
    name:
      - slack
      - yq
  become: true
  when: lookup('env','CI') == ""


- name: Install packages
  become: yes
  package:
    state: latest
    name:
      - python3-pip
      - python3-openssl
      - "openjdk-{{ debian_openjdk_version }}-jdk"
      - fonts-powerline
      # Ubuntu / Gnome utils
      - ubuntu-restricted-extras
      - gnome-tweaks
      - nautilus-image-converter
      - network-manager-openvpn-gnome

      # Compiling tools
      - libbz2-dev
      - llvm
      - libffi-dev
      - cmake

      # Rust / Alacritty things
      - libssl-dev
      - libcairo2-dev
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev

      - potool
      - gstreamer1.0-plugins-bad

- name: Download Node.JS Repo script
  become: yes
  get_url:
    url: "https://deb.nodesource.com/setup_{{debian_node_version}}.x"
    dest: /tmp/set-up-node.sh
    force: yes
    mode: ug+rx

- name: Set up Node repo
  become: true
  script: /tmp/set-up-node.sh

- name: Add Python Poetry & AWS CLI
  command: python3 -m pip install --user poetry awscli
