version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker build -t workstation-playbook:latest .
        no_output_timeout: 20m
