version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker build -t workstation-playbook:latest
