version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.10
    steps:
      - checkout
      - run:
          name: Add PPA tools
          command: apt update && apt install -y software-properties-common
      - run:
          name: Add Ansible PPA
          command: apt-add-repository ppa:ansible/ansible && apt update
      - run:
          name: Install Ansible
          command: apt-get install -y ansible
      - run:
          name: Run playbook
          command: ansible-playbook playbook.yml -c localhost -K
