version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.10
    steps:
      - checkout
      - run:
          name: Add Ansible PPA
          command: echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu cosmic main" >> /etc/apt/sources.list && apt update
      - run:
          name: Install Ansible
          command: apt-get install -y ansible
      - run:
          name: Run playbook
          command: ansible-playbook playbook.yml -c localhost
