version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
      - run:
          name: Build in Docker
          command: docker build -t workstation-playbook:latest .
          no_output_timeout: 20m
