---
- name: Configure user for Zsh and Docker
  become: yes
  user:
    name: "{{ user|quote }}"
    generate_ssh_key: yes
    shell: /usr/bin/zsh
    append: yes
    groups: adm, docker

- name: Configure Zsh
  template:
    src: templates/zshrc.in
    dest: "{{ config_dir + '/.zshrc' }}"
    backup: yes

- name: Symlink ZSH config
  file:
    src: "{{ config_dir + '/.zshrc' }}"
    dest: "{{ ansible_env.HOME + '/.zshrc' }}"
    state: link
    force: true

- name: Remove ~/.conf/
  file:
    path: "{{ ansible_env.HOME + '/.conf/' }}"
    state: absent

- name: Create Tmux config dir
  file:
    path: "{{ tmux_conf_dir}}"
    state: directory

- name: Configure Tmux
  template:
    src: templates/tmux.conf
    dest: "{{ tmux_conf_path }}"

- name: Default to Alacritty
  become: true
  shell: update-alternatives --install /etc/alternatives/x-terminal-emulator alacritty "{{ ansible_env.HOME }}/.cargo/bin/alacritty" 1

- stat:
    path: /usr/bin/gsettings
  register: gsettings

- name: Sort out window dragging
  command: gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier '<Alt>'
  when: gsettings.stat.executable is defined and gsettings.stat.executable

- name: Remap move to workspace left keys
  command: gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Control><Super>Left']"
  when: gsettings.stat.executable is defined and gsettings.stat.executable

- name: Remap move to workspace right keys
  command: gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Control><Super>Right']"
  when: gsettings.stat.executable is defined and gsettings.stat.executable

- name: Increase file watchers
  become: true
  command: echo "fs.inotify.max_user_watches=524288" >>> /etc/sysctl.conf

